/*
----------------------------------------------------------------------------------------------------------
    Name:	EW_Dog
    Author:	Edward V. Weber
    Language:	Java
    Date:	2023-08-08
    Purpose:	The purpose of this program is to create a Dog class that extends an Animal base class
                and then adds values for Breed and Color.  Also it will override the printAdoptionStatus
                method.
----------------------------------------------------------------------------------------------------------
    Change Log
----------------------------------------------------------------------------------------------------------
    Who		Date		Reason
    EVW		2023-08-08	Original Version of Code
----------------------------------------------------------------------------------------------------------
*/
public class EW_Dog extends EW_Animal {

    private String strBreed = "Unknown";
    private String strColor = "Unknown";

    // three constructors initializing these private variables and the extended variables
    public EW_Dog(){
        strAnimalName = "Unnamed Dog";
        strBreed = "Unknown";
        strColor = "Unknown";
        blnIsAdoptable = false;
        blnNeedsMeds = false;
        blnNeedsShots = true;
    }
    public EW_Dog(String strNewName){
        strAnimalName = strNewName;
        strBreed = "Unknown";
        strColor = "Unknown";
        blnIsAdoptable = false;
        blnNeedsMeds = false;
        blnNeedsShots = true;
    }
    public EW_Dog(String strNewName, String strNewBreed, String strNewColor){
        strAnimalName = strNewName;
        strBreed = strNewBreed;
        strColor = strNewColor;
        blnIsAdoptable = false;
        blnNeedsMeds = false;
        blnNeedsShots = true;
    }    
    /*
     * Accessors (autogenerated)
     */
    public String getStrBreed() {
        return strBreed;
    }
    public String getStrColor() {
        return strColor;
    }
    /*
     * Mutators (autogenerated - still don't like the names!)
     */
    public void setStrBreed(String strBreed) {
        this.strBreed = strBreed;
    }
    public void setStrColor(String strColor) {
        this.strColor = strColor;
    }
    @Override
    public void printAdoptionStatus() {
        System.out.println("This dog's adoption status is:");
        System.out.println("\tShelter Name:\t" + strAnimalName);
        System.out.println("\tBreed:\t\t" + strBreed);
        System.out.println("\tColor:\t\t" + strColor);
        System.out.println("\tNeeds Shots?\t" + blnNeedsShots);
        System.out.println("\tNeeds Meds?\t" + blnNeedsMeds);
        System.out.println("\tAdoptable Now?\t" + blnIsAdoptable);
    }
}